http_port: 8080
env: "dev"
eth_url: "wss://ethereum-sepolia-rpc.publicnode.com"
owner: "ADMIN"
secret: "JWT_SECRET_KEY"
token:
  address: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
  file_path: "ERC20"
  symbol: "USDC"
  decimals: 6
db:
  region: "us-east-1"
  table: "ECOMMERCE"
