version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  web3-ecommerce:
    image: web3-ecommerce:${IMG_VER}
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./deployment/application-local.yaml:/app/application.yaml
      - ./deployment/abi/erc-20.json:/app/erc-20.json
      - ./deployment/owner:/app/owner
      - ./deployment/secret:/app/secret
